# Brand Colors
ROYAL_BLUE = '#3447AA'
POWDER_PINK = '#FBEAEB'

# Background
BACKGROUND = '#F0F0F0'

# Surfaces
SURFACE = '#FBFBFB'
SURFACE_ALT = '#FFFFFF'
SURFACE_ALT2 = '#F0F0F0'

# Borders
BORDER = '#E4E8F1'
BORDER_SOFT = '#D7DEEA'

# Text
TEXT_PRIMARY = '#222831'
TEXT_SECONDARY = '#6B7280'
TEXT_INVERSE = '#FAFAFA'

# Text Accent
TEXT_TINT = '#2D3448'
TEXT_TINT_HOVER = '#2B3348'
TEXT_ON_PRIMARY_SOFT = '#F3F2FF'

# Interactive
PRIMARY = ROYAL_BLUE
PRIMARY_HOVER = '#2E3F97'
PRIMARY_PRESSED = '#24347D'

SECONDARY = '#7287E5'
SECONDARY_STRONG = '#5555D5'
SECONDARY_SOFT = '#ECE9FF'

ACCENT = POWDER_PINK

# Status
SUCCESS = '#2ca24d'
FAILED = '#d23b3b'
FAILED_HOVER = '#BF3232'